"""Header and footer generators for PDF reports."""

from typing import Any, Dict


def _shape(text: str, font_name: str) -> str:
    """Apply Arabic reshaping if text contains Arabic characters."""
    import re

    if not re.search(r"[\u0600-\u06FF]", text):
        return text
    try:
        import arabic_reshaper
        from bidi.algorithm import get_display

        return get_display(arabic_reshaper.reshape(text))
    except ImportError:
        return text


class HeaderBuilder:
    def __init__(self, font_name: str, styles: Dict[str, Any]) -> None:
        self.font_name = font_name
        self.styles = styles

    def build(self, report_type: str, dto: Any, language: str = "ar") -> list:
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.platypus import Paragraph, Spacer

        titles = {
            "official": {"ar": "تقرير رسمي - CCI-FT2", "en": "CCI-FT2 Official Report"},
            "technical": {"ar": "الملخص التقني", "en": "Technical Summary"},
            "arabic": {"ar": "تقرير رسمي", "en": "Official Report"},
        }
        lang = language if language in ("ar", "en") else "ar"
        title_text = titles.get(report_type, {}).get(lang, "Report")
        title_text = _shape(title_text, self.font_name)

        base = getSampleStyleSheet()["Title"]
        title_style = ParagraphStyle(
            "CustomTitle",
            parent=base,
            fontName=self.font_name,
            alignment=1,
        )

        elements = []
        elements.append(Paragraph(title_text, title_style))
        elements.append(Spacer(1, 12))
        return elements


class FooterBuilder:
    def __init__(self, font_name: str, styles: Dict[str, Any]) -> None:
        self.font_name = font_name
        self.styles = styles

    def build(self, dto: Any) -> list:
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.platypus import Paragraph, Spacer

        base = getSampleStyleSheet()["Normal"]
        info_style = ParagraphStyle(
            "CustomFooter",
            parent=base,
            fontName=self.font_name,
        )
        elements = [Spacer(1, 24)]
        elements.append(Paragraph("Generated by CCI-FT2", info_style))
        return elements
