"""Header and footer generators for PDF reports.

This module will provide simple builder classes used by the new PDF engine.
"""

from typing import Any, Dict

# postpone reportlab imports until build time to allow tests to run without it


class HeaderBuilder:
    def __init__(self, font_name: str, styles: Dict[str, Any]) -> None:
        self.font_name = font_name
        self.styles = styles

    def build(self, report_type: str, dto: Any) -> list:
        """Return a list of Flowable elements representing the header.

        For now we include a simple title depending on the report type.  In later
        phases this will include logos, signatures, and dynamic data.
        """
        # import inside method so module can be imported without reportlab
        from reportlab.platypus import Paragraph, Spacer

        title_text = {
            "official": "CCI-FT2 Official Report",
            "technical": "Technical Summary",
            "arabic": "تقرير رسمي",
        }.get(report_type, "Report")
        # ensure we always have a Paragraph style; fall back to a sample style
        title_style = self.styles.get("Title")
        if title_style is None:
            from reportlab.lib.styles import getSampleStyleSheet

            title_style = getSampleStyleSheet()["Title"]

        elements = []
        # build Paragraph with style regardless of what we were given
        elements.append(Paragraph(title_text, title_style))
        elements.append(Spacer(1, 12))
        return elements


class FooterBuilder:
    def __init__(self, font_name: str, styles: Dict[str, Any]) -> None:
        self.font_name = font_name
        self.styles = styles

    def build(self, dto: Any) -> list:
        # import locally
        from reportlab.platypus import Paragraph, Spacer

        page_text = "Generated by CCI-FT2"
        # ensure we at least have a normal style for the footer text
        try:
            info_style = self.styles.get("Info")
        except Exception:
            info_style = None
        if info_style is None:
            from reportlab.lib.styles import getSampleStyleSheet

            info_style = getSampleStyleSheet()["Normal"]

        elements = [Spacer(1, 24)]
        elements.append(Paragraph(page_text, info_style))
        return elements
