"""Unit tests for the new PDFGenerator stub (Phase 1).
"""

import pytest

from src.domain.dtos.device_report_dto import DeviceReportDTO
from src.infrastructure.adapters.reporting.new_pdf_engine import PDFGenerator
from src.utils.time import utc_now_iso

# determine if reportlab is installed so tests can be skipped gracefully
try:
    import reportlab  # type: ignore  # noqa: F401

    HAS_REPORTLAB = True
except ImportError:
    HAS_REPORTLAB = False


@pytest.fixture(autouse=True)
def skip_if_no_reportlab():
    if not HAS_REPORTLAB:
        pytest.skip("reportlab not installed")


def make_dto():
    return DeviceReportDTO(
        device_id="UNIT-001",
        vaccine_type="Test",
        total_records=1,
        excursions=[],
        final_status="safe",
        scientific_rationale="unit check",
        generated_at=utc_now_iso(),
    )


def test_generate_returns_bytes():
    gen = PDFGenerator()
    pdf = gen.generate(make_dto())
    assert isinstance(pdf, (bytes, bytearray))
    # when ReportLab is available we expect a real document, not the
    # trivial 193-byte fallback generated by previous logic.  Size > 1KB is a
    # reasonable proxy for 'real' content.
    assert len(pdf) > 1000
    assert pdf.startswith(b"%PDF")


def test_generate_with_report_type():
    gen = PDFGenerator()
    pdf = gen.generate(make_dto(), report_type="technical")
    assert pdf.startswith(b"%PDF")


def test_generate_contains_page():
    gen = PDFGenerator()
    pdf = gen.generate(make_dto(), report_type="official")
    # ensure either full generator produced page object or fallback minimal
    assert b"/Type /Page" in pdf
    # when reportlab present expect more than minimal size
    if len(pdf) > 200:
        assert b"/Type /Page" in pdf
